describe('Pizza test, sprint 7 challenge', () => {
    it('Inputa "Ecem" yazıldığında, #name-input value "Ecem" olmalı.', () => {
        cy.visit('http://localhost:3000/pizza')
        cy.get('#name-input').type('Ecem')
        cy.get('#name-input').should('have.value', 'Ecem')
    })
    it('Birden fazla malzeme seçilebilmeli.', () => {
        cy.visit('http://localhost:3000/pizza')
        cy.get('#topping-pepperoni').check()
        cy.get('#topping-pepperoni').should('be.checked')
        cy.get('#topping-sausage').check()
        cy.get('#topping-sausage').should('be.checked')
        cy.get('#topping-dana-fume').check()
        cy.get('#topping-dana-fume').should('be.checked')
        cy.get('#topping-grilled-chicken').check()
        cy.get('#topping-grilled-chicken').should('be.checked')
        cy.get('#topping-onions').check()
        cy.get('#topping-onions').should('be.checked')
        cy.get('#topping-green-peppers').check()
        cy.get('#topping-green-peppers').should('be.checked')
        cy.get('#topping-tomatoes').check()
        cy.get('#topping-tomatoes').should('be.checked')
        cy.get('#topping-black-olives').check()
        cy.get('#topping-black-olives').should('be.checked')
    })
    it('Formu gönderen bir test yazın.', () => {
        cy.visit('http://localhost:3000/pizza')
        cy.get('#name-input').type('Ecem')
        cy.get('#adres-input').type('Adres')
        cy.get('#pizza').select('pizza1')
        cy.get('#pizza').select('pizza2')
        cy.get('#pizza').select('pizza3')
        cy.get('#size-dropdown').select('Küçük')
        cy.get('#size-dropdown').select('Orta')
        cy.get('#size-dropdown').select('Büyük')
        cy.get('#topping-pepperoni').check()
        cy.get('#topping-sausage').check()
        cy.get('#topping-dana-fume').check()
        cy.get('#topping-grilled-chicken').check()
        cy.get('#topping-onions').check()
        cy.get('#topping-green-peppers').check()
        cy.get('#topping-tomatoes').check()
        cy.get('#topping-black-olives').check()
        cy.get('#special-text').type('Pizza dilimlensin.')
        
        cy.intercept('POST', 'https://reqres.in/api/orders', {
            statusCode: 201,
        }).as('postOrder')
        cy.get('#order-button').click()
        cy.wait('@postOrder')
    })
})

